In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
arr_1d.ndim

1

In [5]:
arr_1d.shape

(5,)

In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
arr_2d.ndim

2

In [8]:
arr_2d = np.array([[[1, 2, 3]], [[4, 5, 6]]])

In [9]:
arr_2d.ndim

3

In [10]:
arr_float = np.array([1, 2, 3], dtype=np.float64)

In [11]:
arr_float

array([1., 2., 3.])

In [12]:
zeros_arr = np.zeros((3, 4))

In [13]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
zeros_arr = np.ones((3, 4))

In [15]:
zeros_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
zeros_arr = np.eye(3)

In [17]:
zeros_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
range_arr = np.arange(0, 100, 20)

In [22]:
type(range_arr)

numpy.ndarray

In [26]:
type(list(range(10)))

list

In [27]:
linspace_arr = np.linspace(0, 1, 5) 

In [28]:
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
linspace_arr1 = np.linspace(2, 10, 100) 

In [30]:
linspace_arr1

array([ 2.        ,  2.08080808,  2.16161616,  2.24242424,  2.32323232,
        2.4040404 ,  2.48484848,  2.56565657,  2.64646465,  2.72727273,
        2.80808081,  2.88888889,  2.96969697,  3.05050505,  3.13131313,
        3.21212121,  3.29292929,  3.37373737,  3.45454545,  3.53535354,
        3.61616162,  3.6969697 ,  3.77777778,  3.85858586,  3.93939394,
        4.02020202,  4.1010101 ,  4.18181818,  4.26262626,  4.34343434,
        4.42424242,  4.50505051,  4.58585859,  4.66666667,  4.74747475,
        4.82828283,  4.90909091,  4.98989899,  5.07070707,  5.15151515,
        5.23232323,  5.31313131,  5.39393939,  5.47474747,  5.55555556,
        5.63636364,  5.71717172,  5.7979798 ,  5.87878788,  5.95959596,
        6.04040404,  6.12121212,  6.2020202 ,  6.28282828,  6.36363636,
        6.44444444,  6.52525253,  6.60606061,  6.68686869,  6.76767677,
        6.84848485,  6.92929293,  7.01010101,  7.09090909,  7.17171717,
        7.25252525,  7.33333333,  7.41414141,  7.49494949,  7.57

In [33]:
random_int = np.random.randint(1, 10, size=(3, 3))

In [34]:
random_int

array([[6, 6, 1],
       [5, 2, 4],
       [2, 5, 4]])

In [41]:
random_float = np.random.random((40, 4))

In [42]:
random_float

array([[0.1674769 , 0.61888672, 0.2737789 , 0.836578  ],
       [0.86597407, 0.77007618, 0.37966175, 0.87722307],
       [0.83083149, 0.42962137, 0.52339235, 0.84837929],
       [0.96415133, 0.90924133, 0.16774339, 0.09522355],
       [0.50094252, 0.82411216, 0.51709334, 0.78744392],
       [0.85734344, 0.35995296, 0.46506939, 0.58972227],
       [0.69410497, 0.80728347, 0.09973456, 0.27535706],
       [0.29935392, 0.30974089, 0.44426479, 0.41684804],
       [0.96622324, 0.14375086, 0.84014531, 0.58296057],
       [0.08155497, 0.88903972, 0.13834215, 0.8114721 ],
       [0.50351156, 0.63825259, 0.51546761, 0.14462807],
       [0.08583296, 0.30908817, 0.91337688, 0.28290491],
       [0.12982346, 0.36995237, 0.17876756, 0.4297116 ],
       [0.61677819, 0.3135409 , 0.59170924, 0.28663771],
       [0.49075174, 0.68998653, 0.68920411, 0.61139846],
       [0.76495957, 0.89186898, 0.80081264, 0.28120015],
       [0.35912603, 0.57760391, 0.03781367, 0.74659418],
       [0.23038983, 0.68190654,

In [43]:
normal_dist = np.random.normal(0, 1, (3, 3)) 

In [44]:
normal_dist

array([[-1.45678098, -1.02460576, -0.91635046],
       [-0.59407908, -0.04437635,  0.65756961],
       [ 1.65548499, -1.22880481,  0.44193259]])

In [48]:
# Setting seed for reproducibility
np.random.seed(42)
reproducible1 = np.random.random(5)

In [46]:
np.random.seed(25)
reproducible = np.random.random(5)

In [47]:
reproducible

array([0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013])

In [49]:
reproducible1

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [50]:
sample_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [51]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
sample_array.shape

(3, 4)

In [53]:
sample_array.dtype

dtype('int32')

In [54]:
sample_array.ndim

2

In [55]:
sample_array.size

12

In [56]:
sample_array.itemsize

4

In [57]:
arr_1d = np.array([10, 20, 30, 40, 50])

In [58]:
arr_1d

array([10, 20, 30, 40, 50])

In [59]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [60]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [62]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
(data > 3) & (data < 8)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [65]:
np.random.randn(3, 3)

array([[ 0.27904129,  1.01051528, -0.58087813],
       [-0.52516981, -0.57138017, -0.92408284],
       [-2.61254901,  0.95036968,  0.81644508]])

In [66]:
original = np.arange(12) 

In [67]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
arr4 = original.reshape(3,4)

In [73]:
arr4.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [74]:
arr4.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
np.array([1, 2, 3, 4, 5],ndmin=32)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3, 4,
                                      5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [78]:
arr_2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr_2d.mean()

5.0

In [81]:
arr_2d.sum()

45

In [82]:
arr_2d.max()

9

In [83]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
sample_array[0]

array([1, 2, 3, 4])

In [86]:
sample_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
sample_array[:,2]

array([ 3,  7, 11])

In [89]:
sample_array.mean(axis=0)

array([5., 6., 7., 8.])

In [116]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [91]:
a

array([1, 2, 3, 4])

In [92]:
b

array([5, 6, 7, 8])

In [93]:
a*3

array([ 3,  6,  9, 12])

In [94]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
arr_2d*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [97]:
arr_2d/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [98]:
arr_2d+sample_array

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [99]:
sample_array%3

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]], dtype=int32)

In [102]:
arr_2d**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [103]:
a.dot(b)

70

In [104]:
b

array([5, 6, 7, 8])

In [112]:
a = np.array([1, 2, 3, 4],ndmin=2)

In [113]:
a

array([[1, 2, 3, 4]])

In [117]:
b.dot(a)

70

In [119]:
angles = np.array([0, np.pi/4, np.pi/2, np.pi])

In [120]:
angles

array([0.        , 0.78539816, 1.57079633, 3.14159265])

In [121]:
np.sin(angles)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 1.22464680e-16])

In [122]:
np.cos(angles)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -1.00000000e+00])

In [123]:
values = np.array([1, 2, 3, 4])

In [125]:
values

array([1, 2, 3, 4])

In [126]:
np.exp(values)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [127]:
np.log(values)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [128]:
np.sqrt(values)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [129]:
decimals = np.array([1.234, 2.567, 3.891])

In [130]:
np.round(decimals, 2)

array([1.23, 2.57, 3.89])

In [131]:
np.ceil(decimals)

array([2., 3., 4.])

In [132]:
np.floor(decimals)

array([1., 2., 3.])

In [133]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [134]:
arr1

array([[1, 2],
       [3, 4]])

In [137]:
arr2

array([[5, 6],
       [7, 8]])

In [136]:
arr3

array([[ 9, 10],
       [11, 12]])

In [138]:
v_stack = np.vstack((arr1, arr2))

In [139]:
v_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [140]:
h_stack = np.hstack((arr1, arr2))

In [141]:
h_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [142]:
concat_axis0 = np.concatenate((arr1, arr2), axis=0)

In [143]:
concat_axis0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [144]:
large_array = np.arange(20).reshape(4, 5)

In [145]:
large_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [149]:
split_result = np.split(large_array, 4, axis=0) 

In [150]:
split_result

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [151]:
data_with_missing = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.inf])

In [152]:
data_with_missing

array([ 1.,  2., nan,  4.,  5., inf])

In [153]:
import time as tm

size_1 = 10000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 7.085577011108398
numpy = 0.09168076515197754
